FROM camunda/camunda-bpm-platform:run-latest

# add custom configuration files here
# For example, to use PostgreSQL, we can set environment variables in docker-compose.yml
# or copy a default.yml / production.yml here.

# EXPOSE 8080
