CREATE USER 'moodleuser'@'%' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON moodle.* TO 'moodleuser'@'%' WITH GRANT OPTION;
CREATE USER 'root'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
