services:

  fzl-nginx:
    image: nginx:stable-alpine
    container_name: fzl-nginx
    ports:
      - "8055:80"
    volumes:
      - ./../projects/var_www_html:/var/www/html
      - ./fzl-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fzl-php8-fpm
    networks:
      - fzl-network

  fzl-php8-fpm:
    build:
      context: ./containers/fzl-php8-fpm
      dockerfile: Dockerfile
    container_name: fzls-php8-fpm
    volumes:
      - ./../projects/var_www_html/:/var/www/html
    networks:
      - fzl-network

  fzl-mysql:
    image: mysql:8.0
    container_name: fzl-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # Senha do usuário root do MySQL
      MYSQL_DATABASE: fzl_db # Nome do banco de dados a ser criado
      MYSQL_USER: eteczl_user # Usuário do banco de dados
      MYSQL_PASSWORD: 1234 # Senha do usuário do banco de dados
    volumes:
      - fzl-db-data:/var/lib/mysql # Volume nomeado para persistência dos dados do MySQL
    networks:
      - fzl-network

  fzl-karaf-camel-integration:
    build:
      context: ./containers/fzl-karaf-camel-integration
      dockerfile: Dockerfile
      ports:        
    container_name: fzl-karaf-camel-integration
    volumes:
      - ./../projects/karaf_bundles:/opt/karaf/deploy_bundles:ro # Bundles para deploy manual (leitura apenas)
      - ./../projects/karaf_deploy_dir:/opt/karaf/deploy # Diretório de hot deploy do Karaf
      - ./../projects/karaf_input_dir:/opt/karaf/input_data # Diretório de entrada para rotas Camel
      - ./../projects/karaf_output_dir:/opt/karaf/output_data # Diretório de saída para rotas Camel
      - ./../projects/karaf_project_sources_dir:/opt/karaf/sources:rw # bundles sources do projeto (leitura apenas)
      - fzl-karaf-data:/opt/karaf/data
    networks:
      - fzl-network
    restart: unless-stopped # Boa prática para serviços

  fzl-angular-frontend:
    image: fzl-angular-frontend:0.0.1
    build:
      context: ./containers/fzl-angular-frontend
      dockerfile: Dockerfile
      target: development
    container_name: fzl-angular-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./../projects/fzl-angular-frontend:/app

  fzl-emacs:
    image: fzl-emacs:0.0.1
    build:
      context: ./containers/fzl-emacs
      dockerfile: Dockerfile
    container_name: fzl-emacs
    volumes:
      - ./:/fzlhome
      
  fzl-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8889:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=fzl-mysql
    depends_on:
      - fzl-mysql
    networks:
      - fzl-network

  # Definição de volumes nomeados para persistência de dados
  volumes:
    fzl-db-data: # Volume para os dados do MySQL

  # Definição de redes personalizadas para comunicação entre os serviços
  networks:
    fzl-network:
      driver: bridge # Tipo de rede (bridge é o padrão e mais comum)
