FROM docker.elastic.co/kibana/kibana:8.15.0

#RUN /usr/share/kibana/bin/kibana-plugin install canvas

COPY kibana.yml /usr/share/kibana/config/kibana.yml

EXPOSE 5601

CMD ["/usr/local/bin/kibana-docker"]
